---
# inherit the next configuration down the chain (see above for the order)
inherit: true
filter:
  paths: ["src/"]

imports:
  - php
build:
  environment:
    php:
      version: 7.0

checks:
    php: true
tools:
  sensiolabs_security_checker: true
  php_mess_detector:
    config:
       ruleset: 'phpmd.xml'
  php_code_sniffer:
    filter:
      excluded-paths: [ spec/*, examples/* ]
    config:
      standard: "Symfony"
  php_analyzer:
    filter:
      excluded-paths: [ 'spec/*', 'examples/*' ]
  php_sim:
    filter:
      excluded-paths: [ 'spec/*', 'examples/*' ]

build_failure_conditions:
    - 'issues.label("coding-style").new.exists'

filter:
  paths: [ src/* ]
  excluded_paths:
    - docs/*
    - vendor/*
