---
# Travis build file
language: php
sudo: false

matrix:
  include:
    - php: 5.6
    - php: hhvm
    - php: 7.0
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
- |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...${TRAVIS_BRANCH}"
    fi
    IGNORE_LIST='(\.md|rst$)|(LICENSE$)|(\.scrutinizer\.yml$)|(\.(editorconfig|gitignore|gitattributes)$)|(^(docs|examples))/'
    git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE "${IGNORE_LIST}" || {
      echo "No build files updated, stopping build process."
      exit
    }
    if [ "${TRAVIS_PHP_VERSION}" != 'hhvm' ]; then phpenv config-rm xdebug.ini; fi
    composer selfupdate

script:
  - bin/test --no-fix
...
